services:
  - type: web
    name: yana-backend
    runtime: python
    rootDir: backend
    buildCommand: pip install -r requirements.txt && python manage.py collectstatic --noinput
    preDeployCommand: python manage.py migrate
    startCommand: gunicorn yana.wsgi --log-file -
    envVars:
      - key: DEBUG
        value: "False"
      - key: ALLOWED_HOSTS
        value: yana-backend.onrender.com
      - key: EXPOSE_OTP_IN_RESPONSE
        value: "True"
      - key: CORS_ALLOW_ALL_ORIGINS
        value: "False"
      - key: CORS_ALLOWED_ORIGINS
        value: https://yana-frontend.onrender.com
      - key: CSRF_TRUSTED_ORIGINS
        value: https://yana-backend.onrender.com,https://yana-frontend.onrender.com
      - key: SECRET_KEY
        generateValue: true
      - key: DATABASE_URL
        fromDatabase:
          name: yana-db
          property: connectionString

  - type: web
    name: yana-frontend
    runtime: static
    rootDir: frontend
    buildCommand: ""
    staticPublishPath: .

databases:
  - name: yana-db
    plan: free
