# Generated by Django 5.0.4 on 2026-03-24 18:34

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fleet', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Rider',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('aadhaar_number', models.CharField(blank=True, max_length=12)),
                ('dl_number', models.CharField(blank=True, max_length=20)),
                ('dl_expiry', models.DateField(blank=True, null=True)),
                ('bank_account', models.CharField(blank=True, max_length=20)),
                ('ifsc_code', models.CharField(blank=True, max_length=11)),
                ('bank_name', models.CharField(blank=True, max_length=100)),
                ('onboarding_status', models.CharField(choices=[('applied', 'Applied'), ('docs_submitted', 'Documents Submitted'), ('kyc_pending', 'KYC Pending'), ('kyc_verified', 'KYC Verified'), ('active', 'Active'), ('rejected', 'Rejected'), ('suspended', 'Suspended')], default='applied', max_length=30)),
                ('rejection_reason', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('activated_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('hub', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='riders', to='fleet.hub')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='rider_profile', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_riders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'riders',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='OnboardingEvent',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('event_type', models.CharField(max_length=50)),
                ('from_status', models.CharField(blank=True, max_length=30)),
                ('to_status', models.CharField(blank=True, max_length=30)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='onboarding.rider')),
            ],
            options={
                'db_table': 'onboarding_events',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RiderDocument',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('doc_type', models.CharField(choices=[('aadhaar', 'Aadhaar Card'), ('dl', 'Driving License'), ('bank_passbook', 'Bank Passbook'), ('photo', 'Passport Photo')], max_length=30)),
                ('file', models.FileField(upload_to='rider_docs/%Y/%m/')),
                ('verification_status', models.CharField(choices=[('pending', 'Pending Review'), ('verified', 'Verified'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('rejection_note', models.TextField(blank=True)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('rider', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='onboarding.rider')),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='verified_docs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'rider_documents',
                'unique_together': {('rider', 'doc_type')},
            },
        ),
    ]
